# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170820_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cel',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
