# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supermarket', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finish', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(related_name='cart_prod', to='products.Product')),
                ('supermarket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_cart', to='supermarket.Supermarket')),
            ],
        ),
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.UUIDField()),
                ('qtd', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='products.Product')),
            ],
        ),
    ]
