# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='productt', to='products.Product'),
        ),
    ]
