# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
        ('cart', '0002_auto_20170909_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='supermarket',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supermarket_cart', to='supermarket.Supermarket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(related_name='product_cart', to='products.Product'),
        ),
    ]
