# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supermarket',
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='product', to='core.Product'),
        ),
        migrations.AddField(
            model_name='supermarket',
            name='products',
            field=models.ManyToManyField(related_name='products', to='core.Product'),
        ),
    ]
