# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-24 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170823_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarket',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
    ]
