# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-24 17:34
from __future__ import unicode_literals

import brazilnum.cnpj
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, validators=[brazilnum.cnpj.validate_cnpj]),
        ),
    ]
