# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 05:53
from __future__ import unicode_literals

import brazilnum.cpf
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[brazilnum.cpf.validate_cpf])),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Endereço')),
                ('cep', models.CharField(max_length=8, verbose_name='Cep')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
